# Generated by Django 3.0.3 on 2020-03-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='equation',
        ),
    ]
