# Generated by Django 3.0.3 on 2020-02-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20200209_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='id',
        ),
        migrations.AlterField(
            model_name='graph',
            name='equation',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
